### ISSUE TITLE
Allowing more (all?) domains for CORS

### ISSUE THREAD

**Issue by Drazcmd** [giving-a-fuck-about-climate-change/carbondoomsday#117]
Given that this api consists entirely of side-effect free GETs, I think it'd be fairly safe to allow more/any domains in production. Assuming I'm looking in the correct spot (not too familiar with django stuff, so it's entirely possible I'm not!) right now it's just whitelisting carbondoomsday.com (see https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/master/carbondoomsday/settings.py#L242)

I believe the change would be pretty simple, probably just need something along the lines of:
```
class Production(CORSHeaderAllowAll, Dokku, OpbeatCredentials, Base):
    """The production environment."""
    ENVIRONMENT = 'Production'
    ALLOWED_HOSTS = [
        'api.carbondoomsday.com'
    ]
```

**Comment by lwm** [comment]
Yes, thanks for raising @Drazcmd, and I just saw that @titojankowski raised:

> does that mean that no one else can use our API?

And it just hit me that yes, this must be the case! I've just re-read the docs:

> https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts

It must be set but it appears we can just default to `*`.

As @Drazcmd mentioned, quite rightly (and in the right place!):

> Given that this api consists entirely of side-effect free GETs,  I think it'd be fairly safe

**Comment by lwm** [comment]
Ah but wait, this isn't related to the CORS issue 😨 

@Drazcmd, the django docs for `ALLOWED_HOSTS` refers to:

> A list of strings representing the host/domain names that this Django site can serve.

So this should always be set to `carbondoomsday.com`. Right, wrapped my brain around that again.

@grady-lad said:

> Tried testing out the new endpoint, but ran into COR's issues again, as I am requesting from localhost

This is because we used to have a test deployment (`carbondoomsday-test.herokuapp.com`) which allowed had the **CORS** setting of https://github.com/ottoyiu/django-cors-headers#cors_origin_allow_all which means CORS was not an issue. Now, we only have a production API which only allows `carbondoomsday.com` (the production chart) to do CORS managed requests. Localhost is blocked. That is the correct setting for production.

SO! What I will do now is re-setup a testing domain for the api and fixup the carbon-inferno configuration to point to that and use the `CORS_ORIGIN_ALLOW_ALL` again. Then, testing locally for the chart can work.

**Comment by lwm** [comment]
OK, CORS unrestricted app is up at https://api-test.carbondoomsday.com/.

Closing off and adding configuration changes to carbon-inferno!
