### ISSUE TITLE
Add pagination for co2 results

### ISSUE THREAD

**Issue by lwm** [giving-a-fuck-about-climate-change/carbondoomsday#17]
There is a lot of them, so we need pagination. Will set to 50. Shout if that is not OK.

**Comment by YPCrumble** [comment]
@lwm getting data for the "all" chart currently requires two lookups, one to get the `limit` parameter and a second to get all results based on that `limit` parameter. Removing pagination would make that possible via one query.

I'm not aware of all the endpoints available, but if getting "all" results is the largest possible API call it doesn't seem like pagination is necessary.

I'm also partially asking this because I don't know the "correct" or "RESTful" answer and I'm encountering a very similar issue on one of my projects, would love to hear your opinion :).

**Comment by lwm** [comment]
> Removing pagination would make that possible via one query.

Later, someone would ask me to re-enable pagination when we get too many results :)

>  don't know the "correct" or "RESTful" answer 

You know, I don't either and I kinda stopped caring after all the flame wars 🔥 

In general, I like the API to be consistent, so defaulting to a limit is good IMHO. AFAIK, the `/api/co2/?ordering=-date?&limit=1` must always be made to get the 'global level' and should it not be possible to optimise from there? Because you will always get the `count` which can be reused later?
